import json
import os
import shutil
import subprocess
import time
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import psycopg
from dotenv import load_dotenv
from yt_dlp import YoutubeDL

load_dotenv(Path(__file__).resolve().parents[2] / ".env")

DB_URL = os.getenv("DATABASE_URL", "")
QUEUE_PROVIDER = os.getenv("QUEUE_PROVIDER", "local")
STORAGE_PROVIDER = os.getenv("STORAGE_PROVIDER", "local")
POLL_INTERVAL_MS = int(os.getenv("WORKER_POLL_INTERVAL_MS", "2000"))
GCS_BUCKET_NAME = os.getenv("GCS_BUCKET_NAME", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
DEEPL_API_KEY = os.getenv("DEEPL_API_KEY", "")
OPENAI_TRANSCRIBE_MODEL = os.getenv("OPENAI_TRANSCRIBE_MODEL", "whisper-1")
OPENAI_TRANSLATE_MODEL = os.getenv("OPENAI_TRANSLATE_MODEL", "gpt-4o-mini")
OPENAI_TRANSCRIBE_MAX_BYTES = int(os.getenv("OPENAI_TRANSCRIBE_MAX_BYTES", str(24 * 1024 * 1024)))
DEFAULT_WORKER_TEMP_DIR = Path(__file__).resolve().parent / "tmp"
WORKER_TEMP_DIR_RAW = os.getenv("WORKER_TEMP_DIR", str(DEFAULT_WORKER_TEMP_DIR))
FFMPEG_LOCATION = os.getenv("FFMPEG_LOCATION", "")

LOCAL_STORAGE_ROOT = Path(__file__).resolve().parents[2] / "local_storage"


def resolve_local_temp_dir(raw_dir: str) -> Path:
    """
    yt-dlp requires a local filesystem path for downloads.
    If someone configures gs:// here, we still need a local temp folder.
    """
    if raw_dir.strip().lower().startswith("gs://"):
        print(f"Ignoring gs:// WORKER_TEMP_DIR for local temp audio: {raw_dir}")
        return DEFAULT_WORKER_TEMP_DIR
    return Path(raw_dir)


WORKER_TEMP_DIR = resolve_local_temp_dir(WORKER_TEMP_DIR_RAW)
LOCAL_STORAGE_ROOT.mkdir(parents=True, exist_ok=True)
WORKER_TEMP_DIR.mkdir(parents=True, exist_ok=True)


def db_conn():
    return psycopg.connect(DB_URL)


def update_job(job_id: str, status: str, progress: int, error: Optional[str] = None, srt_path: Optional[str] = None, vtt_path: Optional[str] = None):
    with db_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE jobs
                SET status = %s,
                    progress_percentage = %s,
                    error_message = %s,
                    srt_path = COALESCE(%s, srt_path),
                    vtt_path = COALESCE(%s, vtt_path),
                    updated_at = NOW()
                WHERE id = %s
                """,
                (status, progress, error, srt_path, vtt_path, job_id),
            )


def fetch_next_local_message() -> Optional[Dict[str, Any]]:
    with db_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, payload
                FROM queue_messages
                WHERE status = 'PENDING'
                ORDER BY created_at ASC
                LIMIT 1
                FOR UPDATE SKIP LOCKED
                """
            )
            row = cur.fetchone()
            if row is None:
                return None

            msg_id, payload = row
            cur.execute(
                """
                UPDATE queue_messages
                SET status = 'PROCESSING', attempts = attempts + 1
                WHERE id = %s
                """,
                (msg_id,),
            )
            return {"id": msg_id, "payload": payload}


def mark_local_message_done(msg_id: int, failed: bool = False):
    status = "FAILED" if failed else "DONE"
    with db_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE queue_messages
                SET status = %s, processed_at = NOW()
                WHERE id = %s
                """,
                (status, msg_id),
            )


def mock_transcribe(source_url: str) -> list[dict]:
    return [
        {"start": 0.0, "end": 2.5, "text": f"Sample transcription from {source_url}"},
        {"start": 2.5, "end": 5.0, "text": "This is generated by StreamSync worker in local mode."},
    ]


def mock_translate(segments: list[dict], target_language: str) -> list[dict]:
    translated = []
    for seg in segments:
        translated.append({**seg, "text": f"[{target_language.upper()}] {seg['text']}"})
    return translated


def cleanup_file(file_path: Path):
    try:
        file_path.unlink(missing_ok=True)
    except Exception:
        pass


def resolve_ffmpeg_executable() -> str:
    if FFMPEG_LOCATION:
        ffmpeg_path = Path(FFMPEG_LOCATION)
        if ffmpeg_path.is_file():
            return str(ffmpeg_path)
        if ffmpeg_path.is_dir():
            candidate = ffmpeg_path / ("ffmpeg.exe" if os.name == "nt" else "ffmpeg")
            if candidate.exists():
                return str(candidate)
    return shutil.which("ffmpeg") or "ffmpeg"


def prepare_audio_for_transcription(audio_path: Path, job_id: str) -> Tuple[Path, Optional[Path]]:
    if audio_path.stat().st_size <= OPENAI_TRANSCRIBE_MAX_BYTES:
        return audio_path, None

    compressed_path = WORKER_TEMP_DIR / f"{job_id}-whisper.mp3"
    ffmpeg = resolve_ffmpeg_executable()
    try:
        subprocess.run(
            [
                ffmpeg,
                "-y",
                "-i",
                str(audio_path),
                "-vn",
                "-ac",
                "1",
                "-ar",
                "16000",
                "-b:a",
                "64k",
                str(compressed_path),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
        )
    except FileNotFoundError as ex:
        raise RuntimeError("Audio file is too large for Whisper and FFmpeg is not installed.") from ex
    except subprocess.CalledProcessError as ex:
        stderr = (ex.stderr or "").strip()
        raise RuntimeError(f"Audio file is too large for Whisper and FFmpeg compression failed: {stderr}") from ex

    if compressed_path.stat().st_size > OPENAI_TRANSCRIBE_MAX_BYTES:
        cleanup_file(compressed_path)
        raise RuntimeError("Audio file is still too large for Whisper after FFmpeg compression.")

    print(f"Compressed audio for Whisper: {audio_path.name} -> {compressed_path.name}")
    return compressed_path, compressed_path


def _find_downloaded_audio(job_id: str, ext: Optional[str] = None) -> Optional[Path]:
    if ext:
        candidate = WORKER_TEMP_DIR / f"{job_id}.{ext}"
        if candidate.exists():
            return candidate
    matches = sorted(WORKER_TEMP_DIR.glob(f"{job_id}.*"), key=lambda p: p.stat().st_mtime, reverse=True)
    for path in matches:
        if path.suffix.lower() in {".m4a", ".webm", ".opus", ".mp3", ".wav", ".mp4", ".ogg"}:
            return path
    return matches[0] if matches else None


def _to_download_error_message(ex: Exception) -> str:
    msg = str(ex).strip()
    lowered = msg.lower()
    if "cloudflare anti-bot challenge" in lowered or "http error 403" in lowered:
        return (
            "Download blocked by Cloudflare (HTTP 403). "
            "Install yt-dlp impersonation dependency and retry with "
            '--extractor-args "generic:impersonate".'
        )
    if "ffmpeg" in lowered:
        return (
            "Nu s-a putut procesa audio-ul cu FFmpeg. "
            "Instaleaza FFmpeg (winget install ffmpeg) sau seteaza FFMPEG_LOCATION in .env."
        )
    return f"Nu s-a putut descarca audio-ul: {msg or 'unknown error'}"


def download_audio(source_url: str, job_id: str) -> Tuple[Optional[Path], Optional[str]]:
    """Download audio from URL. Tries without ffmpeg first, then optional MP3 conversion."""
    output_template = str(WORKER_TEMP_DIR / f"{job_id}.%(ext)s")
    base_opts: dict = {
        "format": "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio/best",
        "outtmpl": output_template,
        "noplaylist": True,
        "quiet": True,
        "no_warnings": True,
        "extractor_args": {"generic": {"impersonate": ["chrome"]}},
    }
    if FFMPEG_LOCATION:
        base_opts["ffmpeg_location"] = FFMPEG_LOCATION

    # 1) Direct audio download (no ffmpeg post-processing)
    direct_error: Optional[str] = None
    mp3_error: Optional[str] = None

    try:
        with YoutubeDL(base_opts) as ydl:
            info = ydl.extract_info(source_url, download=True)
            ext = info.get("ext") if info else None
        found = _find_downloaded_audio(job_id, ext)
        if found:
            print(f"Audio downloaded for {job_id}: {found.name}")
            return found, None
    except Exception as ex:
        direct_error = _to_download_error_message(ex)
        print(f"Audio download (direct) failed for {job_id}: {ex}")

    # 2) Optional: convert to mp3 if ffmpeg is available
    mp3_opts = {
        **base_opts,
        "format": "bestaudio/best",
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "192",
            }
        ],
    }
    try:
        with YoutubeDL(mp3_opts) as ydl:
            ydl.download([source_url])
        found = _find_downloaded_audio(job_id, "mp3")
        if found:
            print(f"Audio downloaded (mp3) for {job_id}: {found.name}")
            return found, None
    except Exception as ex:
        mp3_error = _to_download_error_message(ex)
        print(f"Audio download (ffmpeg/mp3) failed for {job_id}: {ex}")

    return None, mp3_error or direct_error


def transcribe_with_openai(audio_path: Path, job_id: str) -> Optional[list[dict]]:
    if not OPENAI_API_KEY:
        return None
    prepared_audio: Optional[Path] = None
    try:
        from openai import OpenAI

        audio_path, prepared_audio = prepare_audio_for_transcription(audio_path, job_id)
        client = OpenAI(api_key=OPENAI_API_KEY)
        with audio_path.open("rb") as audio_file:
            transcript = client.audio.transcriptions.create(
                model=OPENAI_TRANSCRIBE_MODEL,
                file=audio_file,
                response_format="verbose_json",
            )

        segments = []
        raw_segments = getattr(transcript, "segments", None) or []
        for seg in raw_segments:
            start = float(seg.start)
            end = float(seg.end)
            text = str(seg.text).strip()
            if text:
                segments.append({"start": start, "end": end, "text": text})

        if segments:
            return segments
    except Exception as ex:
        print(f"Whisper transcription failed: {ex}")
    finally:
        if prepared_audio:
            cleanup_file(prepared_audio)
    return None


def translate_with_deepl(segments: list[dict], target_language: str) -> Optional[list[dict]]:
    if not DEEPL_API_KEY:
        return None
    try:
        import deepl

        translator = deepl.Translator(DEEPL_API_KEY)
        translated = []
        deepl_lang = target_language.upper()
        if deepl_lang == "EN":
            deepl_lang = "EN-US"
        for seg in segments:
            result = translator.translate_text(seg["text"], target_lang=deepl_lang)
            translated.append({**seg, "text": str(result.text)})
        return translated
    except Exception as ex:
        print(f"DeepL translation failed: {ex}")
    return None


def translate_with_openai(segments: list[dict], target_language: str) -> Optional[list[dict]]:
    if not OPENAI_API_KEY:
        return None
    try:
        from openai import OpenAI

        client = OpenAI(api_key=OPENAI_API_KEY)
        translated = []
        for seg in segments:
            prompt = (
                f"Translate the following subtitle text to language code '{target_language}'. "
                "Return only the translated text with no extra commentary.\n\n"
                f"Text: {seg['text']}"
            )
            response = client.responses.create(
                model=OPENAI_TRANSLATE_MODEL,
                input=prompt,
                temperature=0.2,
            )
            text = (response.output_text or "").strip()
            translated.append({**seg, "text": text or seg["text"]})
        return translated
    except Exception as ex:
        print(f"OpenAI translation failed: {ex}")
    return None


def format_timestamp_srt(sec: float) -> str:
    hours = int(sec // 3600)
    minutes = int((sec % 3600) // 60)
    seconds = int(sec % 60)
    millis = int((sec - int(sec)) * 1000)
    return f"{hours:02}:{minutes:02}:{seconds:02},{millis:03}"


def format_timestamp_vtt(sec: float) -> str:
    hours = int(sec // 3600)
    minutes = int((sec % 3600) // 60)
    seconds = int(sec % 60)
    millis = int((sec - int(sec)) * 1000)
    return f"{hours:02}:{minutes:02}:{seconds:02}.{millis:03}"


def to_srt(segments: list[dict]) -> str:
    lines = []
    for i, seg in enumerate(segments, 1):
        lines.append(str(i))
        lines.append(f"{format_timestamp_srt(seg['start'])} --> {format_timestamp_srt(seg['end'])}")
        lines.append(seg["text"])
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def to_vtt(segments: list[dict]) -> str:
    lines = ["WEBVTT", ""]
    for seg in segments:
        lines.append(f"{format_timestamp_vtt(seg['start'])} --> {format_timestamp_vtt(seg['end'])}")
        lines.append(seg["text"])
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def save_local_file(relative_path: str, content: str):
    full_path = LOCAL_STORAGE_ROOT / relative_path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    full_path.write_text(content, encoding="utf-8")


def process_job(job_id: str, source_url: str, target_language: str):
    use_real_ai = bool(OPENAI_API_KEY)

    update_job(job_id, "PROCESSING", 10)
    audio_file, download_error = download_audio(source_url, job_id)

    if use_real_ai and not audio_file:
        raise RuntimeError(download_error or "Nu s-a putut descarca audio-ul.")

    try:
        segments: list[dict]
        if audio_file:
            transcribed = transcribe_with_openai(audio_file, job_id)
            if transcribed:
                segments = transcribed
            elif use_real_ai:
                raise RuntimeError("Whisper nu a returnat transcriere. Verifica OPENAI_API_KEY si creditul API.")
            else:
                segments = mock_transcribe(source_url)
        else:
            segments = mock_transcribe(source_url)

        update_job(job_id, "PROCESSING", 50)
        time.sleep(0.2)

        if use_real_ai:
            translated_segments = (
                translate_with_deepl(segments, target_language)
                or translate_with_openai(segments, target_language)
            )
            if not translated_segments:
                raise RuntimeError("Traducerea a esuat (DeepL si OpenAI).")
        else:
            translated_segments = mock_translate(segments, target_language)
        srt_content = to_srt(translated_segments)
        vtt_content = to_vtt(translated_segments)

        now = datetime.now(UTC).strftime("%Y%m%d%H%M%S")
        prefix = f"jobs/{job_id}/{now}-{uuid.uuid4().hex[:8]}"
        srt_path = f"{prefix}.srt"
        vtt_path = f"{prefix}.vtt"

        if STORAGE_PROVIDER == "local":
            save_local_file(srt_path, srt_content)
            save_local_file(vtt_path, vtt_content)
        else:
            from google.cloud import storage

            client = storage.Client()
            bucket = client.bucket(GCS_BUCKET_NAME)
            bucket.blob(srt_path).upload_from_string(srt_content, content_type="text/plain; charset=utf-8")
            bucket.blob(vtt_path).upload_from_string(vtt_content, content_type="text/plain; charset=utf-8")
    finally:
        if audio_file:
            cleanup_file(audio_file)

    update_job(job_id, "COMPLETED", 100, None, srt_path=srt_path, vtt_path=vtt_path)


def run_local_loop():
    print("Worker started in local queue mode")
    while True:
        msg = fetch_next_local_message()
        if not msg:
            time.sleep(POLL_INTERVAL_MS / 1000.0)
            continue

        msg_id = msg["id"]
        payload = msg["payload"]
        job_id = payload["job_id"]
        source_url = payload["source_url"]
        target_language = payload["target_language"]

        try:
            process_job(job_id, source_url, target_language)
            mark_local_message_done(msg_id, failed=False)
            print(f"Processed job {job_id}")
        except Exception as ex:
            update_job(job_id, "FAILED", 100, str(ex))
            mark_local_message_done(msg_id, failed=True)
            print(f"Failed job {job_id}: {ex}")


def run_gcp_loop():
    from google.cloud import pubsub_v1

    project_id = os.getenv("GCP_PROJECT_ID", "")
    subscription_id = os.getenv("GCP_PUBSUB_SUBSCRIPTION", "")
    if not project_id or not subscription_id:
        raise RuntimeError("GCP_PROJECT_ID and GCP_PUBSUB_SUBSCRIPTION are required for gcp mode")

    subscriber = pubsub_v1.SubscriberClient()
    sub_path = subscriber.subscription_path(project_id, subscription_id)

    print("Worker started in GCP Pub/Sub mode")

    def callback(message):
        try:
            payload = json.loads(message.data.decode("utf-8"))
            job_id = payload["job_id"]
            process_job(job_id, payload["source_url"], payload["target_language"])
            message.ack()
            print(f"Processed job {job_id}")
        except Exception as ex:
            try:
                payload = json.loads(message.data.decode("utf-8"))
                update_job(payload["job_id"], "FAILED", 100, str(ex))
            except Exception:
                pass
            message.nack()
            print(f"Failed message: {ex}")

    future = subscriber.subscribe(sub_path, callback=callback)
    future.result()


if __name__ == "__main__":
    if not DB_URL:
        raise RuntimeError("Missing DATABASE_URL")

    if QUEUE_PROVIDER == "gcp":
        run_gcp_loop()
    else:
        run_local_loop()
